pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('user-service') {
                    sh "docker run --rm -v ${env.WORKSPACE}:/app -w /app/user-service maven:3.9.9-jdk-21 mvn clean package"

                }
            }
        }

        stage('Test') {
            steps {
                dir('user-service') {
                    sh 'docker run --rm -v $PWD:/app -w /app/user-service maven:3.9.9-jdk-21 mvn test'
                }
            }
        }

        stage('Archive') {
            steps {
                dir('user-service') {
                    archiveArtifacts artifacts: 'target/*.jar', allowEmptyArchive: true
                }
            }
        }
    }

    post {
        success {
            echo 'user-service built successfully!'
        }
        failure {
            echo 'user-service build failed!'
        }
    }
}
