pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('user-service') {
                    // Run Maven directly
                    sh 'mvn clean package'
                }
            }
        }

        stage('Test') {
            steps {
                dir('user-service') {
                    sh 'mvn test'
                }
            }
        }

        stage('Archive') {
            steps {
                dir('user-service') {
                    archiveArtifacts artifacts: 'target/*.jar', allowEmptyArchive: true
                }
            }
        }
    }

    post {
        success {
            echo 'user-service built successfully!'
        }
        failure {
            echo 'user-service build failed!'
        }
    }
}
